// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE_m2nOTlLPoftrXgu0h-MD7XfaQ85mm0',
    appId: '1:378144589866:web:3b281d1dff5ac80f411b53',
    messagingSenderId: '378144589866',
    projectId: 'onlyaudio-74ba7',
    authDomain: 'onlyaudio-74ba7.firebaseapp.com',
    storageBucket: 'onlyaudio-74ba7.firebasestorage.app',
    measurementId: 'G-JHXVEFJK0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVtxu5TZplfo1enTMzc8WbAJSiYGaprjY',
    appId: '1:378144589866:android:480af8b9e25ac523411b53',
    messagingSenderId: '378144589866',
    projectId: 'onlyaudio-74ba7',
    storageBucket: 'onlyaudio-74ba7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTWn72GZr4G08jSHxhi4kGDj937uqcMfE',
    appId: '1:378144589866:ios:cec1d09cb9bd7c24411b53',
    messagingSenderId: '378144589866',
    projectId: 'onlyaudio-74ba7',
    storageBucket: 'onlyaudio-74ba7.firebasestorage.app',
    iosBundleId: 'com.example.onlyAudio',
  );

}